PrivateAI_GDPR = {
    "category": "GDPR",
    "entity_types": ["GDPR"],
}

PrivateAI_TNO = {
    "category": "TNO'_Selection",
    "entity_types": [
        "DRIVER_LICENSE",
        "EMAIL_ADDRESS",
        "HEALTHCARE_NUMBER",
        "IP_ADDRESS",
        "LOCATION_ADDRESS",
        "LOCATION_ADDRESS_STREET",
        "LOCATION_COORDINATE",
        "LOCATION_ZIP",
        "NAME",
        "NAME_FAMILY",
        "NAME_GIVEN",
        "PASSPORT_NUMBER",
        "PHONE_NUMBER",
        "SSN",
        "VEHICLE_ID",
        "BANK_ACCOUNT",
        "CREDIT_CARD",
        "CREDIT_CARD_EXPIRATION",
        "CVV",
        "NAME_MEDICAL_PROFESSIONAL",
        "NUMERICAL_PII",
        "URL",
        "USERNAME",
    ],
}

DatasetName_To_PrivateAI_Mapping = {
    "IBAN": "BANK_ACCOUNT",
    "URL": "URL",
    "Birthday": "DOB",
    "DutchBelgianDriversLicenseNumber": "DRIVER_LICENSE",
    "BelgianPhoneNumber": "PHONE_NUMBER",
    "EmailAddress": "EMAIL_ADDRESS",
    "CreditCardCVVCode": "CVV",
    "EuropeanVATNumber": "BANK_ACCOUNT",
    "InternationalPhoneNumber": "PHONE_NUMBER",
    "CreditCardExpiryDate": "CREDIT_CARD_EXPIRATION",
    "CreditCardNumber": "CREDIT_CARD",
    "FilePath": "URL",
    "Address": "LOCATION_ADDRESS_STREET",
    "Person": "NAME",
    "DutchPhoneNumber": "PHONE_NUMBER",
    "DutchLicensePlateNumber": "VEHICLE_ID",
    "DutchIdentityDocumentNumber": "PASSPORT_NUMBER",
    "BelgianPassportNumber": "PASSPORT_NUMBER",
    "BelgianLicencePlateNumber": "VEHICLE_ID",
    "DutchVreemdelingenDocumentNumber": "SSN",
    "BelgianIdentityNumber": "SSN",
    "DutchIdentityNumberBSN": "SSN",
    "MACAddress": "NUMERICAL_PII",
    "IPAddress": "IP_ADDRESS",
    "USSocialSecurityNumber": "SSN",
    "UKNationalInsuranceNumber": "SSN",
    "USBankAccountNumber": "BANK_ACCOUNT",
    "AustralianPassportNumber": "PASSPORT_NUMBER",
    "CanadianBankAccountNumber": "BANK_ACCOUNT",
    "CanadianPassportNumber": "PASSPORT_NUMBER",
    "UKDriversLicenseNumber": "DRIVER_LICENSE",
    "AustralianDriversLicenseNumber": "DRIVER_LICENSE",
    "UKUniqueTaxpayerReferenceNumber": "SSN",
    "USIndividualTaxPayerIdentificationNumber": "SSN",
    "AustralianTaxFileNumber": "SSN",
    "UK_USPassportNumber": "PASSPORT_NUMBER",
    "AustralianBankAccountNumber": "BANK_ACCOUNT",
    "Organisation": "ORGANISATION",
}

SyntheticReplacementStrategies = {
    "DRIVER_LICENSE": ("ReplacementStrategy", "license"),
    "EMAIL_ADDRESS": ("Faker", "ascii_safe_email", "internet"),
    "HEALTHCARE_NUMBER": ("ReplacementStrategy", "healthcare_policy"),
    "IP_ADDRESS": ("Faker", "ipv4_private", "internet"),
    "LOCATION_ADDRESS": ("Faker", "address", ("nl_NL", "en_GB")),  ###
    "LOCATION_ADDRESS_STREET": ("Faker", "street_address", ("nl_NL", "en_GB")),
    "LOCATION_COORDINATE": ("ReplacementStrategy", "coordinate"),
    "LOCATION_ZIP": ("Faker", "postcode", ("nl_NL",)),
    "NAME": ("Faker", "name", ("nl_NL", "en_GB")),
    "NAME_FAMILY": ("Faker", "last_name", ("nl_NL", "en_GB")),
    "NAME_GIVEN": ("Faker", "first_name", ("nl_NL", "en_GB")),
    "PASSPORT_NUMBER": ("ReplacementStrategy", "passport"),
    "PHONE_NUMBER": ("Faker", "phone_number", ("nl_NL",)),
    "SSN": ("Faker", "ssn", ("nl_NL",)),
    "VEHICLE_ID": ("Faker", "license_plate_car", ("nl_NL",)),
    "BANK_ACCOUNT": ("Faker", "iban", ("nl_NL",)),
    "CREDIT_CARD": ("Faker", "credit_card_number", "credit_card"),
    "CREDIT_CARD_EXPIRATION": ("Faker", "credit_card_expire", "credit_card"),
    "CVV": ("Faker", "credit_card_security_code", "credit_card"),
    "NAME_MEDICAL_PROFESSIONAL": ("Faker", "name", ("nl_NL", "en_GB"), "Dr. "),
    "NUMERICAL_PII": ("ReplacementStrategy", "number"),
    "URL": ("ReplacementStrategy", "url"),
    # "URL": ("Faker", "uri_path", "internet",
    #         ("https://example.org", "https://example.net", "https://")),
    "USERNAME": ("ReplacementStrategy", "username"),
}
